name: deploy production

on:
  push:
    branches: [main]

env:
  SLACK_CHANNEL: gatheragain_deploy_production
  SLACK_USERNAME: DeployBot
  SLACK_ICON_EMOJI: ':rocket:'
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    env:
      APP_ENV: production
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN_GATHRAGAIN }}
      - run: yarn install

      - run: |
          expo publish --release-channel prod-v1.0
          echo "DEPLOY_STATE=successful" >> $GITHUB_ENV

      - name: Failed Deployment
        if: failure()
        run: echo "DEPLOY_STATE=failed" >> $GITHUB_ENV

      - name: Confirm Deploy State
        if: always()
        run: |
          echo "DEPLOY_STATE: ${{ env.DEPLOY_STATE }}"

      # 成功
      - name: Slack Notification on Success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: Production環境にOTAリリースしました
          SLACK_COLOR: good
      # 失敗
      - name: Slack Notification on Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: Production環境にOTAリリースできませんでした
          SLACK_COLOR: danger
